name: Nx Affected

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

defaults:
  run:
    shell: bash

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Install NPM dependecies
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install cached dependencies
        uses: bahmutov/npm-install@v1

      - name: Test and lint affected libraries
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: ciTest
          affected: 'true'

      - name: SonarCloud Analysis
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: ciSonar
          affected: 'true'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

      - name: Check build works
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: ciBuild
          affected: 'true'

      - name: Setup NPM config
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Version affected libraries
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: version
          affected: 'true'

      - name: Build affected libraries
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: ciBuild
          affected: 'true'

      - name: Deploy to NPM
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: ciDeploy
          affected: 'true'
