name: Nx Affected

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

defaults:
  run:
    shell: bash

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Install NPM dependecies
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install cached dependencies
        uses: bahmutov/npm-install@v1

  test:
    needs: setup
    runs-on: ubuntu-latest
    name: Run tests and linter
    steps:
      - name: Retieve cached npm
        uses: bahmutov/npm-install@v1

      - name: Test and lint affected libraries
        run: yarn affected --target=ciTest --base=main --with-deps

      - name: Upload test
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: |
            coverage/
            lint/

  quality:
    needs: test
    runs-on: ubuntu-latest
    name: Run quality tests
    steps:
      - name: Retieve cached npm
        uses: bahmutov/npm-install@v1

      - name: Download setup
        uses: actions/download-artifact@v2
        with:
          name: test

      - name: SonarCloud Analysis
        run: yarn affected --target=ciSonar --base=main --with-deps

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

      - name: Check build works
        run: yarn affected --target=ciBuild --base=main --with-deps

  build:
    needs: quality
    runs-on: ubuntu-latest
    name: Build and deploy
    steps:
      - name: Retieve cached npm
        uses: bahmutov/npm-install@v1

      - name: Setup NPM config
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Version affected libraries
        run: yarn affected --target version --base=main --with-deps

      - name: Build affected libraries
        run: yarn affected --target=ciBuild --base=main --with-deps
