name: Nx Affected CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  BEFORE_SHA: ${{ github.event.before }}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: git fetch origin main
      - run: yarn install
      - name: Run Affected Tests
        shell: bash
        run: yarn affected:ci:test --base=$BEFORE_SHA
